# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
#export JAVA_HOME=/usr/java/default
export JAVA_HOME=/usr/lib/jvm/java-7-oracle/
export PATH=${JAVA_HOME}/bin:${PATH}
#cac: reducing memory usage from 1024m to 512m
export MAVEN_OPTS="-Xms512m -Xmx512m -XX:MaxPermSize=512m"
